name: create-gitlab-issues
version: 0.1.0.0
github: "yoshimasa36g/create-gitlab-issues"
license: BSD3
author: "yoshimasa36g"
maintainer: "ashihana785@gmail.com"
copyright: "2020 yoshimasa36g"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/create-gitlab-issues#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  create-gitlab-issues-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - create-gitlab-issues

tests:
  create-gitlab-issues-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - create-gitlab-issues
